version: '3.7'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=http://192.168.1.209:11434  # Replace with your NAS IP
      - OLLAMA_HOSTNAME=elmo  # Replace with your NAS hostname
      - PYTHONUNBUFFERED=1
    networks:
      - default

networks:
  default:
    name: jira-agent-net
    driver: bridge
    external: true