version: '3.7'

services:
  web:
    build: .
    command: uvicorn src.web.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
  cli:
    build: .
    command: python src/main.py
    env_file: .env
    stdin_open: true  # Enable interactive input
    tty: true         # Allocate pseudo-TTY
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

networks:
  default:
    name: jira-agent-net
    driver: bridge