version: '3.7'

services:
  jira-agent:
    build: .
    env_file: .env
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - JIRA_SERVER=${JIRA_SERVER}
      - JIRA_USER=${JIRA_USER}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - OLLAMA_REQUEST_TIMEOUT=300000  # Add timeout
    extra_hosts:
      - "elmo:${ELMO_IP}"  # Map hostname to IP
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    networks:
      - jira-net

networks:
  jira-net:
    driver: bridge
    external: true