version: '3.7'

services:
  jira-agent:
    build: .
    env_file: .env
    network_mode: "host"  # Critical for cross-machine communication
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}  # Should be http://<remote-ip>:11434
      - JIRA_SERVER=${JIRA_SERVER}
      - JIRA_USER=${JIRA_USER}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - OLLAMA_REQUEST_TIMEOUT=300
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: ["python", "src/main.py"]

  # Optional: Add redis for rate limiting later
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

networks:
  default:
    name: jira-agent-net
    driver: bridge